export const ADMIN_ROUTE = '/admin' 
export const LOGIN_ROUTE = '/login'
export const ABOUT_ROUTE = '/about'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const ORDER_ROUTE = '/order'
export const PRODUCT_ROUTE = '/productList'
export const PRODUCT_ITEM_ROUTE = '/product' 
export const PROFIL_ROUTE = '/profile' 
export const CONSOLIDATION_ROUTER = '/consolidation'
export const PACKAGE_CREATE_ROUTER = '/package'
export const WAYBILL_ROUTER = '/waybill'
export const WAYBILL_PAGE_ROUTER = '/waybill/page'

